let dados = [
    {
        titulo : "Sarah Cameron",
        descricao : "Sarah Cameron é uma jovem carismática com um espírito rebelde. Ela luta para encontrar seu próprio caminho, desafiando as expectativas da sociedade e buscando seus próprios sonhos.",
        nascimento : "4 de junho, 2003",
        link : "https://outer-banks-netflix.fandom.com/wiki/Sarah_Cameron",     
        ator : "Madelyn Cline",
        tags : "carismática, rebelde, aventureira, sarinha, camarão, camarao,",
    },
    {
        titulo: "John B. Routledge",
        descricao: "John B. é o líder dos Pogues, sempre em busca de seu pai desaparecido e de um tesouro lendário. Seu comprometimento com seus amigos e sua paixão por aventuras o tornam um personagem inspirador.",
        nascimento : "3 de agosto, 2002",
        link: "https://outer-banks-netflix.fandom.com/wiki/John_B._Routledge",
        ator : "Chase Stokes",
        tags : "líder, aventureiro, leal, fedido",
    },
    {
        titulo: "Kiara Carrera",
        descricao: "Kiara, ou Kie, é a mente brilhante do grupo. Com seu amor pela natureza e pelos animais, ela sempre está pronta para apoiar seus amigos e lutar por suas crenças.",
        nascimento : "8 de abril, 2003",
        link: "https://outer-banks-netflix.fandom.com/wiki/Kiara_Carrera",
        ator : "Madison Bailey",
        tags : "inteligente, compassiva, ambientalista",
    },
    {
        titulo: "Pope Heyward",
        descricao: "Pope é o cérebro dos Pogues. Sua inteligência e habilidade para resolver problemas são essenciais para desvendar os mistérios e encontrar o tesouro.",
        nascimento : "6 de setembro, 2002",
        link: "https://outer-banks-netflix.fandom.com/wiki/Pope_Heyward",
        ator : "Jonathan Daviss",
        tags : "inteligente, confiável, resolutivo",
    },
    {
        titulo: "JJ Maybank",
        descricao: "JJ é o amigo divertido e leal dos Pogues. Seu espírito aventureiro e seu coração generoso fazem dele um membro querido do grupo.",
        nascimento : "5 de maio, 2002",
        link: "https://outer-banks-netflix.fandom.com/wiki/JJ_Maybank",
        ator : "Rudy Pankow",
        tags : "divertido, leal, aventureiro",
    },
    {
        titulo : "Cleo Anderson",
        descricao : "Cleo é uma jovem independente e corajosa que se junta aos Pogues em suas aventuras. Ela traz habilidades valiosas e uma nova perspectiva ao grupo.",
        nascimento : "1 de fevereiro, 2002",
        link : "https://outer-banks-netflix.fandom.com/wiki/Cleo",
        ator : "Carlacia Grant",
        tags : "independente, aventureira, habilidosa",
    },
    {
        titulo : "Bob Marley",
        descricao : "Bob é o gato de Kiara, conhecido por sua personalidade distinta e carinhosa. Embora não seja um personagem central, ele é uma presença adorável na vida de Kiara.",
        nascimento: "não especificado",
        link: "não é famoso o suficiente",
        ator : "Primo do Garfiel",
        tags : "gato, carinhoso, adorável",
    },
    {
        titulo: "Ward Cameron",
        descricao: "Ward é o pai de Sarah e um homem de negócios astuto e manipulador. Ele fará o que for necessário para proteger seus interesses e manter sua riqueza.",
        nascimento: "5 de março, 1975",
        link: "https://outer-banks-netflix.fandom.com/wiki/Ward_Cameron",
        ator: "Charles Esten",
        tags: "manipulador, rico, controlador",
    },
    {
        titulo: "Rafe Cameron",
        descricao: "Rafe é o irmão mais velho de Sarah, com uma vida cheia de conflitos internos e decisões perigosas. Seu comportamento impulsivo o coloca frequentemente em problemas.",
        nascimento: "10 de novembro, 1997",
        link: "https://outer-banks-netflix.fandom.com/wiki/Rafe_Cameron",
        ator: "Drew Starkey",
        tags: "problemático, impulsivo, conflitante",
    },
    {
        titulo: "Topper Thornton",
        descricao: "Topper é o ex-namorado de Sarah, um Kook com um temperamento explosivo que frequentemente entra em conflito com os Pogues.",
        nascimento: "25 de junho, 2001",
        link: "https://outer-banks-netflix.fandom.com/wiki/Topper_Thornton",
        ator: "Austin North",
        tags: "ex-namorado, temperamental, rival",
    },
    {
        titulo: "Rose Cameron",
        descricao: "Rose é a madrasta de Sarah e Rafe, conhecida por sua frieza e astúcia. Ela sempre está ao lado de Ward em seus esquemas para garantir seus próprios interesses.",
        nascimento: "17 de julho, 1979",
        link: "https://outer-banks-netflix.fandom.com/wiki/Rose_Cameron",
        ator: "Caroline Arapoglou",
        tags: "fria, calculista, manipuladora",
    },
    {
        titulo: "Barry",
        descricao: "Barry é um traficante local que mantém uma rivalidade com Rafe Cameron. Ele busca vingança por motivos pessoais e é um antagonista significativo.",
        nascimento: "30 de agosto, 1990",
        link: "https://outer-banks-netflix.fandom.com/wiki/Barry",
        ator: "Nicholas Cirillo",
        tags: "traficante, antagonista, vingativo",
    },
    {
        titulo: "Sheriff Peterkin",
        descricao: "Sheriff Peterkin é a xerife de Kildare, que se esforça para manter a ordem e a paz entre os Pogues e os Kooks, frequentemente lidando com situações tensas.",
        nascimento: "12 de dezembro, 1973",
        link: "https://outer-banks-netflix.fandom.com/wiki/Sheriff_Peterkin",
        ator: "Adina Porter",
        tags: "xerife, justa, diplomática",
    },
    {
        titulo: "Deputy Shoupe",
        descricao: "Deputy Shoupe é o assistente do Sheriff Peterkin, envolvido em investigações e ajudando a manter a lei em Kildare.",
        nascimento: "9 de setembro, 1968",
        link: "https://outer-banks-netflix.fandom.com/wiki/Shoupe",
        ator: "Cullen Moss",
        tags: "delegado, investigativo, colaborador",
    },
    {
        titulo: "Big John Routledge",
        descricao: "Big John é o pai de John B., cujo desaparecimento durante a busca pelo tesouro dos Royal Merchant desencadeia as aventuras de seu filho.",
        nascimento: "15 de abril, 1972",
        link: "https://outer-banks-netflix.fandom.com/wiki/Big_John_Routledge",
        ator: "Charles Halford",
        tags: "desaparecido, pai, explorador",
    },
    {
        titulo: "Carla Limbrey",
        descricao: "Carla Limbrey é uma mulher rica e enigmática, com seus próprios motivos para procurar o tesouro. Ela é determinada e não hesita em usar todos os meios necessários.",
        nascimento: "18 de outubro, 1965",
        link: "https://outer-banks-netflix.fandom.com/wiki/Limbrey",
        ator: "Elizabeth Mitchell",
        tags: "rica, misteriosa, determinada",
    },
    {
        titulo: "Wheezie Cameron",
        descricao: "Wheezie é a irmã mais nova de Sarah Cameron. Inteligente e curiosa, ela frequentemente se vê envolvida nos conflitos e dramas da família Cameron.",
        nascimento: "25 de março, 2006",
        link: "https://outer-banks-netflix.fandom.com/wiki/Wheezie_Cameron",
        ator: "Julia Antonelli",
        tags: "inteligente, curiosa, jovem",
    },
    {
        titulo: "Gavin",
        descricao: "Gavin é um dos capangas de Ward Cameron, desempenhando um papel crucial nas atividades ilegais e nos conflitos com os Pogues.",
        nascimento: "19 de setembro, 1989",
        link: "https://outer-banks-netflix.fandom.com/wiki/Gavin",
        ator: "Adam Vernier",
        tags: "capanga, envolvido, antagonista",
    },
    {
        titulo: "Luke Maybank",
        descricao: "Luke Maybank é o pai de JJ, conhecido por sua relação problemática com o filho e por seu comportamento abusivo e alcoólatra.",
        nascimento: "30 de outubro, 1974",
        link: "https://outer-banks-netflix.fandom.com/wiki/Luke_Maybank",
        ator: "Gary Weeks",
        tags: "abusivo, alcoólatra, pai",
    },
    {
        titulo: "Heyward",
        descricao: "Heyward é o pai de Pope, um pescador local que também possui uma loja de frutos do mar. Ele trabalha duro e espera o melhor para o futuro de seu filho.",
        nascimento: "18 de dezembro, 1970",
        link: "https://outer-banks-netflix.fandom.com/wiki/Heyward",
        ator: "E. Roger Mitchell",
        tags: "pescador, trabalhador, pai",
    },
    {
        titulo: "Tommy Sowell",
        descricao: "Tommy Sowell é um pescador local que também está envolvido em atividades ilícitas, muitas vezes colaborando com Ward Cameron.",
        nascimento: "2 de maio, 1966",
        link: "https://outer-banks-netflix.fandom.com/wiki/Tommy_Sowell",
        ator: "Gregory Alan Williams",
        tags: "pescador, envolvido, ilícito",
    },
    {
        titulo: "Lana Grubbs",
        descricao: "Lana é uma mulher enigmática que ajuda os Pogues em sua busca pelo tesouro. Sua assistência é crucial, mas suas motivações permanecem misteriosas.",
        nascimento: "27 de junho, 1968",
        link: "https://outer-banks-netflix.fandom.com/wiki/Lana_Grubbs",
        ator: "CC Castillo",
        tags: "misteriosa, enigmática, aliada",
    },
    {
        titulo: "Scooter Grubbs",
        descricao: "Scooter é o marido de Lana e um pescador local. Envolvido com o mistério do Royal Merchant, sua história tem um desfecho trágico.",
        nascimento: "12 de novembro, 1970",
        link: "https://outer-banks-netflix.fandom.com/wiki/Scooter_Grubbs",
        ator: "David Ury",
        tags: "pescador, trágico, envolvido",
    }
];
